services:
  nginx:
    image: tiangolo/nginx-rtmp
    env_file: .env
    ports:
      - ${HTTP_PORT}:${HTTP_PORT}
      - ${RTMP_PORT}:${RTMP_PORT}
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/rtmp.conf:/etc/nginx/conf.d/rtmp.conf
      - ./nginx/http.conf:/etc/nginx/conf.d/http.conf
      - ./ffmpeg/full.m3u:/var/www/html/full.m3u
    networks:
      - stream
  ffmpeg:
    image: ffmpeg-i
    build:
      context: ./ffmpeg
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - ./ffmpeg/media:/media
      - ./ffmpeg/main:/media/main
      - ./ffmpeg/run.sh:/media/run.sh
    depends_on:
      - nginx
    networks:
      - stream
networks:
  stream:
    driver: bridge